package com.salilvnair.packagemonitor.event.type;

/**
 * @author Salil V Nair
 */
public enum PackageMonitorEventType {
    TABLE_PANEL_DATA,
    ENABLE_TABLE_ROW_SELECTION,
    DISABLE_TABLE_ROW_SELECTION,
    SHOW_LOADING,
    HIDE_LOADING,
    DISPOSE_LOADING,
    SHOW_UPDATE_BTN,
    HIDE_UPDATE_BTN,
    SHOW_TOOLBAR_PANEL,
    HIDE_TOOLBAR_PANEL,
    SHOW_TOOLBAR_DIFF_PANEL,
    HIDE_TOOLBAR_DIFF_PANEL,
    ENABLE_FORCE_REFRESH,
    DISABLE_FORCE_REFRESH,
    REPLACE_TABLE_DATA,
    NG_LIB_UPDATED_EVENT
}
